project_id = "wnlyhixhnqjyduqcwyep"

[functions.send-qr-email]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = true

[functions.upload-banner]
verify_jwt = false

[functions.self-register]
verify_jwt = false