// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnlyhixhnqjyduqcwyep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubHloaXhobnFqeWR1cWN3eWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzg5NjUsImV4cCI6MjA3MjkxNDk2NX0.GOLuGIDcjc2wqFIaAXVv7BlR0J5xxIBwjO4EcYutR2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});